version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "impact/no-changelog-required"
      - "github_actions"
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/templates"
    schedule:
      interval: "daily"
    labels:
      - "impact/no-changelog-required"
      - "github_actions"
      - "dependencies"
      - "templates"
    