name: Update
on:
  push:
    branches: [main]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            service:
              - 'templates/service/**'
            infra:
              - 'templates/infra/**'

      # - uses: bjerkio/kopier@main
      #   if: steps.changes.outputs.infra == 'true'
      #   with:
      #     github-search: org:tabetalt topic:infra -repo:tabetalt/infra-core
      #     base-path: templates/infra/
      #     github-token: ${{ secrets.PAYTRON_GITHUB_TOKEN }}

      - uses: bjerkio/kopier@main
        if: steps.changes.outputs.service == 'true'
        with:
          query: org:tabetalt topic:service
          base-path: templates/service/
          github-token: ${{ secrets.PAYTRON_GITHUB_TOKEN }}
          head: automated-kopier

